import { createRouter, createWebHistory } from 'vue-router'
import type { RouteRecordRaw } from 'vue-router'
import HomeView from '../views/HomeView.vue'
import ProjectsView from '../views/ProjectsView.vue'
import StorybookView from '../views/StorybookView.vue'

const projectRoutes: RouteRecordRaw[] = [
  { path: 'todo-list',          component: () => import('../views/projects/01-TodoList.vue')          },
  { path: 'calculator',         component: () => import('../views/projects/02-Calculator.vue')         },
  { path: 'weather-widget',     component: () => import('../views/projects/03-WeatherWidget.vue')      },
  { path: 'quiz-app',           component: () => import('../views/projects/04-QuizApp.vue')            },
  { path: 'notes-app',          component: () => import('../views/projects/05-NotesApp.vue')           },
  { path: 'shopping-cart',      component: () => import('../views/projects/06-ShoppingCart.vue')       },
  { path: 'countdown-timer',    component: () => import('../views/projects/07-CountdownTimer.vue')     },
  { path: 'expense-tracker',    component: () => import('../views/projects/08-ExpenseTracker.vue')     },
  { path: 'markdown-preview',   component: () => import('../views/projects/09-MarkdownPreview.vue')    },
  { path: 'image-carousel',     component: () => import('../views/projects/10-ImageCarousel.vue')      },
  { path: 'password-generator', component: () => import('../views/projects/11-PasswordGenerator.vue') },
  { path: 'color-picker',       component: () => import('../views/projects/12-ColorPicker.vue')        },
  { path: 'currency-converter', component: () => import('../views/projects/13-CurrencyConverter.vue')  },
  { path: 'word-counter',       component: () => import('../views/projects/14-WordCounter.vue')        },
  { path: 'bmi-calculator',     component: () => import('../views/projects/15-BMICalculator.vue')      },
  { path: 'pomodoro-timer',     component: () => import('../views/projects/16-PomodoroTimer.vue')      },
  { path: 'memory-game',        component: () => import('../views/projects/17-MemoryGame.vue')         },
  { path: 'number-guessing',    component: () => import('../views/projects/18-NumberGuessing.vue')     },
  { path: 'dice-roller',        component: () => import('../views/projects/19-DiceRoller.vue')         },
  { path: 'random-quote',       component: () => import('../views/projects/20-RandomQuote.vue')        },
  { path: 'theme-toggle',       component: () => import('../views/projects/21-ThemeToggle.vue')        },
  { path: 'typing-test',        component: () => import('../views/projects/22-TypingTest.vue')         },
  { path: 'flashcards',         component: () => import('../views/projects/23-Flashcards.vue')         },
  { path: 'recipe-card',        component: () => import('../views/projects/24-RecipeCard.vue')         },
  { path: 'kanban-board',       component: () => import('../views/projects/25-KanbanBoard.vue')        },
  { path: 'stopwatch',          component: () => import('../views/projects/26-Stopwatch.vue')          },
  { path: 'digital-clock',      component: () => import('../views/projects/27-DigitalClock.vue')       },
  { path: 'unit-converter',     component: () => import('../views/projects/28-UnitConverter.vue')      },
  { path: 'palindrome-checker', component: () => import('../views/projects/29-PalindromeChecker.vue')  },
  { path: 'star-rating',            component: () => import('../views/projects/30-StarRating.vue')           },
  { path: 'age-calculator',         component: () => import('../views/projects/31-AgeCalculator.vue')        },
  { path: 'tip-calculator',         component: () => import('../views/projects/32-TipCalculator.vue')        },
  { path: 'habit-tracker',          component: () => import('../views/projects/33-HabitTracker.vue')         },
  { path: 'poll-creator',           component: () => import('../views/projects/34-PollCreator.vue')          },
  { path: 'gradient-generator',     component: () => import('../views/projects/35-GradientGenerator.vue')    },
  { path: 'text-to-speech',         component: () => import('../views/projects/36-TextToSpeech.vue')         },
  { path: 'loan-calculator',        component: () => import('../views/projects/37-LoanCalculator.vue')       },
  { path: 'fibonacci-visualizer',   component: () => import('../views/projects/38-FibonacciVisualizer.vue')  },
  { path: 'regex-tester',           component: () => import('../views/projects/39-RegexTester.vue')          },
  { path: 'json-formatter',         component: () => import('../views/projects/40-JsonFormatter.vue')        },
  { path: 'base-converter',         component: () => import('../views/projects/41-BaseConverter.vue')        },
  { path: 'morse-code',             component: () => import('../views/projects/42-MorseCode.vue')            },
  { path: 'calendar',               component: () => import('../views/projects/43-Calendar.vue')             },
  { path: 'tic-tac-toe',            component: () => import('../views/projects/44-TicTacToe.vue')            },
  { path: 'hangman',                component: () => import('../views/projects/45-Hangman.vue')              },
  { path: 'coin-flip',              component: () => import('../views/projects/46-CoinFlip.vue')             },
  { path: 'color-guessing-game',    component: () => import('../views/projects/47-ColorGuessingGame.vue')    },
  { path: 'timezone-converter',     component: () => import('../views/projects/48-TimezoneConverter.vue')    },
  { path: 'lorem-ipsum',            component: () => import('../views/projects/49-LoremIpsum.vue')           },
  { path: 'roman-numerals',         component: () => import('../views/projects/50-RomanNumerals.vue')        },
  { path: 'prime-checker',          component: () => import('../views/projects/51-PrimeChecker.vue')         },
  { path: 'anagram-checker',        component: () => import('../views/projects/52-AnagramChecker.vue')       },
  { path: 'drawing-canvas',         component: () => import('../views/projects/53-DrawingCanvas.vue')        },
  { path: 'rock-paper-scissors',    component: () => import('../views/projects/54-RockPaperScissors.vue')    },
  { path: 'pixel-art',              component: () => import('../views/projects/55-PixelArt.vue')             },
  { path: 'speed-math',             component: () => import('../views/projects/56-SpeedMath.vue')            },
  { path: 'text-case-converter',    component: () => import('../views/projects/57-TextCaseConverter.vue')    },
  { path: 'compound-interest',      component: () => import('../views/projects/58-CompoundInterest.vue')     },
  { path: 'url-encoder',            component: () => import('../views/projects/59-UrlEncoder.vue')           },
  { path: 'metronome',              component: () => import('../views/projects/60-Metronome.vue')            },
  { path: 'grocery-list',           component: () => import('../views/projects/61-GroceryList.vue')          },
  { path: 'contact-book',           component: () => import('../views/projects/62-ContactBook.vue')          },
  { path: 'vigenere-cipher',        component: () => import('../views/projects/63-VigenereCipher.vue')       },
  { path: 'mood-tracker',           component: () => import('../views/projects/64-MoodTracker.vue')          },
  { path: 'bracket-matcher',        component: () => import('../views/projects/65-BracketMatcher.vue')       },
  { path: 'minesweeper',            component: () => import('../views/projects/66-Minesweeper.vue')          },
  { path: 'wordle',                 component: () => import('../views/projects/67-Wordle.vue')               },
  { path: 'password-strength',      component: () => import('../views/projects/68-PasswordStrength.vue')     },
  { path: 'multiplication-table',   component: () => import('../views/projects/69-MultiplicationTable.vue')  },
  { path: 'discount-calculator',    component: () => import('../views/projects/70-DiscountCalculator.vue')   },
  { path: 'number-to-words',        component: () => import('../views/projects/71-NumberToWords.vue')        },
  { path: 'accordion-faq',          component: () => import('../views/projects/72-AccordionFAQ.vue')         },
  { path: 'typewriter-effect',      component: () => import('../views/projects/73-TypewriterEffect.vue')     },
  { path: 'autocomplete-search',    component: () => import('../views/projects/74-AutocompleteSearch.vue')   },
  { path: 'progress-wizard',        component: () => import('../views/projects/75-ProgressWizard.vue')       },
  { path: 'color-contrast',         component: () => import('../views/projects/76-ColorContrast.vue')        },
  { path: 'snake-game',             component: () => import('../views/projects/77-SnakeGame.vue')            },
  { path: 'playlist-manager',       component: () => import('../views/projects/78-PlaylistManager.vue')      },
  { path: 'ascii-art',              component: () => import('../views/projects/79-AsciiArt.vue')             },
  { path: 'event-countdown',        component: () => import('../views/projects/80-EventCountdown.vue')       },
]

const routes: RouteRecordRaw[] = [
  { path: '/', component: HomeView },
  { path: '/projects', component: ProjectsView },
  { path: '/storybook', component: StorybookView },
  ...projectRoutes.map((r) => ({
    path: `/projects/${r.path}`,
    component: r.component!,
  })) as RouteRecordRaw[],
]

const router = createRouter({
  history: createWebHistory(),
  routes,
  scrollBehavior: () => ({ top: 0 }),
})

export default router
