export interface Project {
  id: number
  slug: string
  title: string
  description: string
  tag: string
}

export const projects: Project[] = [
  { id: 1,  slug: 'todo-list',           title: 'Todo List',              description: 'Add, complete, and delete tasks with localStorage persistence.',                    tag: 'State'       },
  { id: 2,  slug: 'calculator',          title: 'Calculator',             description: 'Full-featured arithmetic calculator with expression display.',                       tag: 'Logic'       },
  { id: 3,  slug: 'weather-widget',      title: 'Weather Widget',         description: 'Search cities and view mock weather data with condition icons.',                     tag: 'UI'          },
  { id: 4,  slug: 'quiz-app',            title: 'Quiz App',               description: 'Multiple-choice quiz with score tracking and results screen.',                       tag: 'State'       },
  { id: 5,  slug: 'notes-app',           title: 'Notes App',              description: 'Create and delete sticky notes with localStorage persistence.',                      tag: 'LocalStorage'},
  { id: 6,  slug: 'shopping-cart',       title: 'Shopping Cart',          description: 'Add/remove products, update quantities, and compute total.',                         tag: 'State'       },
  { id: 7,  slug: 'countdown-timer',     title: 'Countdown Timer',        description: 'Set a duration and watch it count down to zero with an alert.',                      tag: 'Timer'       },
  { id: 8,  slug: 'expense-tracker',     title: 'Expense Tracker',        description: 'Track income and expenses with a running balance.',                                  tag: 'Finance'     },
  { id: 9,  slug: 'markdown-preview',    title: 'Markdown Preview',       description: 'Live side-by-side Markdown editor and rendered HTML preview.',                       tag: 'Text'        },
  { id: 10, slug: 'image-carousel',      title: 'Image Carousel',         description: 'Auto-advancing image slideshow with manual nav controls.',                           tag: 'UI'          },
  { id: 11, slug: 'password-generator',  title: 'Password Generator',     description: 'Generate strong passwords with configurable length and character sets.',             tag: 'Utility'     },
  { id: 12, slug: 'color-picker',        title: 'Color Picker',           description: 'RGB sliders with live preview and HEX/RGB code output.',                             tag: 'UI'          },
  { id: 13, slug: 'currency-converter',  title: 'Currency Converter',     description: 'Convert amounts between USD, EUR, GBP, JPY, CAD and AUD.',                           tag: 'Finance'     },
  { id: 14, slug: 'word-counter',        title: 'Word Counter',           description: 'Count words, characters, sentences and estimated reading time.',                      tag: 'Text'        },
  { id: 15, slug: 'bmi-calculator',      title: 'BMI Calculator',         description: 'Calculate Body Mass Index from height and weight with category label.',               tag: 'Health'      },
  { id: 16, slug: 'pomodoro-timer',      title: 'Pomodoro Timer',         description: '25/5 minute work-break cycle timer with session counter.',                            tag: 'Timer'       },
  { id: 17, slug: 'memory-game',         title: 'Memory Game',            description: 'Flip emoji cards to find all matching pairs.',                                        tag: 'Game'        },
  { id: 18, slug: 'number-guessing',     title: 'Number Guessing',        description: 'Guess a secret 1-100 number with hot/cold hints.',                                   tag: 'Game'        },
  { id: 19, slug: 'dice-roller',         title: 'Dice Roller',            description: 'Roll 1–6 dice with animated results and a roll history.',                             tag: 'Game'        },
  { id: 20, slug: 'random-quote',        title: 'Random Quote Generator', description: 'Display inspirational quotes with shuffle and copy-to-clipboard.',                   tag: 'UI'          },
  { id: 21, slug: 'theme-toggle',        title: 'Theme Toggle',           description: 'Switch between light and dark themes with a live preview.',                           tag: 'UI'          },
  { id: 22, slug: 'typing-test',         title: 'Typing Speed Test',      description: 'Measure WPM and accuracy while typing a passage.',                                   tag: 'Game'        },
  { id: 23, slug: 'flashcards',          title: 'Flashcards',             description: 'Study flip-cards with question/answer pairs and progress tracking.',                  tag: 'Education'   },
  { id: 24, slug: 'recipe-card',         title: 'Recipe Card',            description: 'Browse a recipe with dynamic ingredient scaling by serving size.',                    tag: 'UI'          },
  { id: 25, slug: 'kanban-board',        title: 'Kanban Board',           description: 'Move tasks between Todo, In Progress, and Done columns.',                             tag: 'Productivity'},
  { id: 26, slug: 'stopwatch',           title: 'Stopwatch',              description: 'Precision stopwatch with start/stop/lap/reset functionality.',                        tag: 'Timer'       },
  { id: 27, slug: 'digital-clock',       title: 'Digital Clock',          description: 'Live digital clock with date and 12/24-hour toggle.',                                 tag: 'Timer'       },
  { id: 28, slug: 'unit-converter',      title: 'Unit Converter',         description: 'Convert length, weight, and temperature between common units.',                       tag: 'Utility'     },
  { id: 29, slug: 'palindrome-checker',  title: 'Palindrome Checker',     description: 'Check if a word or phrase is a palindrome with step-by-step display.',               tag: 'Text'        },
  { id: 30, slug: 'star-rating',            title: 'Star Rating',               description: 'Interactive 5-star rating widget with hover effects and labels.',                     tag: 'UI'          },
  { id: 31, slug: 'age-calculator',         title: 'Age Calculator',            description: 'Calculate exact age in years, months, days, hours, and minutes from a birthdate.',     tag: 'Utility'     },
  { id: 32, slug: 'tip-calculator',         title: 'Tip Calculator',            description: 'Calculate tip amount and split the bill evenly among any number of people.',             tag: 'Finance'     },
  { id: 33, slug: 'habit-tracker',          title: 'Habit Tracker',             description: 'Track daily habits, mark completions, and visualize weekly streaks.',                    tag: 'Productivity'},
  { id: 34, slug: 'poll-creator',           title: 'Poll Creator',              description: 'Create a poll with custom options and vote to see live percentage results.',              tag: 'State'       },
  { id: 35, slug: 'gradient-generator',     title: 'Gradient Generator',        description: 'Build CSS gradients visually with color pickers, angle and copy-to-clipboard.',          tag: 'UI'          },
  { id: 36, slug: 'text-to-speech',         title: 'Text to Speech',            description: 'Convert any text to speech with voice, rate, and pitch controls via Web Speech API.',    tag: 'API'         },
  { id: 37, slug: 'loan-calculator',        title: 'Loan Calculator',           description: 'Compute monthly payments, total interest, and an amortization schedule.',                tag: 'Finance'     },
  { id: 38, slug: 'fibonacci-visualizer',   title: 'Fibonacci Visualizer',      description: 'Animate the Fibonacci sequence and display the golden-ratio spiral.',                    tag: 'Math'        },
  { id: 39, slug: 'regex-tester',           title: 'Regex Tester',              description: 'Test regular expressions against a string and highlight all matches.',                   tag: 'Utility'     },
  { id: 40, slug: 'json-formatter',         title: 'JSON Formatter',            description: 'Format, minify, and validate JSON with syntax error reporting.',                         tag: 'Utility'     },
  { id: 41, slug: 'base-converter',         title: 'Base Converter',            description: 'Convert numbers between decimal, binary, octal, and hexadecimal.',                       tag: 'Math'        },
  { id: 42, slug: 'morse-code',             title: 'Morse Code Translator',     description: 'Translate text to Morse code and back, with audio playback of dots and dashes.',         tag: 'Text'        },
  { id: 43, slug: 'calendar',               title: 'Monthly Calendar',          description: 'Navigate months, add events to any date, and view upcoming events.',                     tag: 'Productivity'},
  { id: 44, slug: 'tic-tac-toe',            title: 'Tic-Tac-Toe',              description: 'Play Tic-Tac-Toe against an unbeatable minimax AI opponent.',                            tag: 'Game'        },
  { id: 45, slug: 'hangman',                title: 'Hangman',                   description: 'Guess the hidden word letter by letter before the hangman is drawn.',                    tag: 'Game'        },
  { id: 46, slug: 'coin-flip',              title: 'Coin Flip',                 description: 'Flip an animated coin and track the history of heads and tails results.',                tag: 'Game'        },
  { id: 47, slug: 'color-guessing-game',    title: 'Color Guessing Game',       description: 'Guess which color swatch matches the displayed RGB or HEX value.',                      tag: 'Game'        },
  { id: 48, slug: 'timezone-converter',     title: 'Timezone Converter',        description: 'Convert a time from one timezone to multiple others around the world.',                  tag: 'Utility'     },
  { id: 49, slug: 'lorem-ipsum',            title: 'Lorem Ipsum Generator',     description: 'Generate customizable placeholder text by paragraph, sentence, or word count.',         tag: 'Utility'     },
  { id: 50, slug: 'roman-numerals',         title: 'Roman Numeral Converter',   description: 'Convert integers (1–3999) to Roman numerals and back.',                                 tag: 'Math'        },
  { id: 51, slug: 'prime-checker',          title: 'Prime Number Checker',      description: 'Check if a number is prime and find all primes within a range using a sieve.',          tag: 'Math'        },
  { id: 52, slug: 'anagram-checker',        title: 'Anagram Checker',           description: 'Check if two words are anagrams of each other with a letter-frequency breakdown.',      tag: 'Text'        },
  { id: 53, slug: 'drawing-canvas',         title: 'Drawing Canvas',            description: 'Freehand drawing on an HTML canvas with color, brush size, and eraser.',                tag: 'UI'          },
  { id: 54, slug: 'rock-paper-scissors',    title: 'Rock Paper Scissors',       description: 'Play Rock Paper Scissors against a computer opponent with score tracking.',              tag: 'Game'        },
  { id: 55, slug: 'pixel-art',              title: 'Pixel Art Editor',          description: 'Paint a 16×16 grid pixel-by-pixel with a color palette and export as CSS.',             tag: 'UI'          },
  { id: 56, slug: 'speed-math',             title: 'Speed Math Quiz',           description: 'Answer arithmetic problems as fast as possible in a 60-second challenge.',               tag: 'Game'        },
  { id: 57, slug: 'text-case-converter',    title: 'Text Case Converter',       description: 'Convert text to camelCase, PascalCase, snake_case, kebab-case, and more.',              tag: 'Text'        },
  { id: 58, slug: 'compound-interest',      title: 'Compound Interest',         description: 'Project investment growth with compound interest and a year-by-year breakdown.',         tag: 'Finance'     },
  { id: 59, slug: 'url-encoder',            title: 'URL Encoder / Decoder',     description: 'Encode and decode URL components and full URLs with a live preview.',                   tag: 'Utility'     },
  { id: 60, slug: 'metronome',              title: 'Metronome',                 description: 'Adjustable BPM metronome with a visual flash and accent on beat one.',                   tag: 'Music'       },
  { id: 61, slug: 'grocery-list',           title: 'Grocery List',              description: 'Categorized grocery list with check-off, quantities, and localStorage.',                 tag: 'Productivity'},
  { id: 62, slug: 'contact-book',           title: 'Contact Book',              description: 'Add, search, and delete contacts stored in localStorage.',                               tag: 'LocalStorage'},
  { id: 63, slug: 'vigenere-cipher',        title: 'Vigenère Cipher',           description: 'Encrypt and decrypt text with the classic Vigenère substitution cipher.',               tag: 'Security'    },
  { id: 64, slug: 'mood-tracker',           title: 'Mood Tracker',              description: 'Log your daily mood with an emoji and note, and view a history chart.',                  tag: 'Health'      },
  { id: 65, slug: 'bracket-matcher',        title: 'Bracket Matcher',           description: 'Check if brackets in an expression are balanced and highlight mismatches.',              tag: 'Utility'     },
  { id: 66, slug: 'minesweeper',            title: 'Minesweeper',               description: 'Classic 9×9 Minesweeper game with flagging and mine detection.',                        tag: 'Game'        },
  { id: 67, slug: 'wordle',                 title: 'Wordle Clone',              description: 'Guess the hidden 5-letter word in 6 tries with color-coded feedback.',                  tag: 'Game'        },
  { id: 68, slug: 'password-strength',      title: 'Password Strength Meter',  description: 'Analyse a password against security rules and show a visual strength score.',           tag: 'Security'    },
  { id: 69, slug: 'multiplication-table',   title: 'Multiplication Table',      description: 'Interactive times table grid with row/column highlighting on hover.',                   tag: 'Education'   },
  { id: 70, slug: 'discount-calculator',    title: 'Discount Calculator',       description: 'Calculate final price after percentage discount, tax, and cashback.',                    tag: 'Finance'     },
  { id: 71, slug: 'number-to-words',        title: 'Number to Words',           description: 'Convert any integer up to 1 trillion into its English word representation.',            tag: 'Text'        },
  { id: 72, slug: 'accordion-faq',          title: 'Accordion FAQ',             description: 'Expandable FAQ accordion with smooth open/close animation.',                            tag: 'UI'          },
  { id: 73, slug: 'typewriter-effect',      title: 'Typewriter Effect',         description: 'Animated typewriter that cycles through a list of phrases with cursor blink.',          tag: 'UI'          },
  { id: 74, slug: 'autocomplete-search',    title: 'Autocomplete Search',       description: 'Type to filter a list of items with keyboard navigation and highlight.',                tag: 'UI'          },
  { id: 75, slug: 'progress-wizard',        title: 'Progress Wizard',           description: 'Multi-step form wizard with validation, progress bar, and review step.',                tag: 'UI'          },
  { id: 76, slug: 'color-contrast',         title: 'Color Contrast Checker',    description: 'Check foreground/background contrast ratio against WCAG AA/AAA guidelines.',            tag: 'Accessibility'},
  { id: 77, slug: 'snake-game',             title: 'Snake Game',                description: 'Classic snake game on an HTML canvas with score and increasing speed.',                 tag: 'Game'        },
  { id: 78, slug: 'playlist-manager',       title: 'Playlist Manager',          description: 'Build and manage a music playlist with drag-style reordering and fake player UI.',      tag: 'Music'       },
  { id: 79, slug: 'ascii-art',              title: 'ASCII Art Generator',       description: 'Convert text to large ASCII art using block-character fonts.',                          tag: 'Text'        },
  { id: 80, slug: 'event-countdown',        title: 'Event Countdown',           description: 'Add named events with dates and count down days, hours, minutes, and seconds.',          tag: 'Timer'       },
]
